
import "./globals.css";


export const metadata = {
  title: "Weather forecast",
  description: "Generated by create Raushan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="w-full h-screen bg-zinc-800"> 
        {children}
      </body>
    </html>
  );
}
